### ISSUE TITLE
Why you are using 2 resets?

### ISSUE THREAD

**Issue by ahmadalfy** [LinKassem/CSEN1060#4]
You are already using normalize.css ... Why using another reset?

https://github.com/LinKassem/CSEN1060/blob/master/styles/style.css#L1-L75

**Comment by LinKassem** [comment]
@ahmadalfy I like Reset.css because it un-styles the elements completely. For example the h1 element will have 0 margins after using Reset.css, so it just saves me the effort of thinking 'where did that margin come from?'.  And from what I understand is that Normalize.css help fix a lot of cross browser issues. That's why I used them together.

**Comment by ahmadalfy** [comment]
You have a point. As long as you understand the consequences and the differences between both then there is no problem using both of them.
